# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTObzR3oDJbcx5yxyIUaixdYOgBlwt_p
"""

!pip install plotly pandas openpyxl -q

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from google.colab import files
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# 1. UPLOAD INTERFACE
print("Please upload your Attrition Dataset (Excel or CSV):")
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# Load data based on file extension
if file_name.endswith('.csv'):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

# 2. MODELING & PREDICTION (Logistic Regression)
# Select only numeric features for the model
features = ['Satisfaction', 'Evaluation', 'Projects', 'Monthly_Hours', 'Tenure', 'Salary_Level']
X = df[features]
y = df['Attrition']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = LogisticRegression()
model.fit(X_scaled, y)

# Add prediction results to the dataframe
df['Risk_Score'] = (model.predict_proba(X_scaled)[:, 1] * 100).round(2)
df['Status'] = df['Risk_Score'].apply(lambda x: 'High Risk' if x > 70 else ('Medium Risk' if x > 40 else 'Low Risk'))

# 3. AUTOMATIC DASHBOARD GENERATION
print("\n" + "="*50)
print("🎯 ATTRITION PREDICTION DASHBOARD GENERATED")
print("="*50)

# --- Chart 1: Attrition Risk per Employee ---
fig1 = px.bar(df, x='Employee_ID', y='Risk_Score', color='Status',
             title='Individual Employee Attrition Risk (%)',
             color_discrete_map={'High Risk': 'red', 'Medium Risk': 'orange', 'Low Risk': 'green'})
fig1.show()

# --- Chart 2: Feature Importance (Analyze Factors) ---
importance = np.abs(model.coef_[0])
feat_importance = pd.DataFrame({'Feature': features, 'Importance': importance}).sort_values(by='Importance', ascending=False)
fig2 = px.pie(feat_importance, values='Importance', names='Feature',
             title='Impact Factors Analysis (What drives exits?)',
             hole=0.4)
fig2.show()

# --- Chart 3: Satisfaction vs Risk Score ---
fig3 = px.scatter(df, x='Satisfaction', y='Risk_Score', size='Monthly_Hours', color='Status',
                 title='Correlation: Satisfaction vs Risk (Size = Monthly Hours)')
fig3.show()

# 4. BONUS: AUTOMATED RETENTION STRATEGY
high_risk_count = len(df[df['Status'] == 'High Risk'])
print(f"\n📢 SUMMARY REPORT:")
print(f"- Total Employees Analyzed: {len(df)}")
print(f"- High Risk Employees Detected: {high_risk_count}")
print("\n💡 STRATEGIC RECOMMENDATION:")
if high_risk_count > 0:
    print("Priority: Implement 'Flexible Work Windows' and 'Recognition Programs' for employees with high Monthly Hours.")
else:
    print("Maintain current engagement levels and focus on long-term career pathing.")